var mockResponse = {
   "StatusCode":0,
   "Message":null,
   "ExecutionTime":327,
   "ResponseData":{
      "LatestUpdate":"2014-09-19T14:23:28",
      "DataAge":12,
      "Metros":[
         {
            "StopAreaName":"Kungstr&auml;dg&aring;rden",
            "GroupOfLine":"Tunnelbanans bl&aring; linje",
            "DisplayTime":"3 min",
            "SafeDestinationName":"Akalla",
            "GroupOfLineId":3,
            "DepartureGroupId":1,
            "PlatformMessage":"T&aring;g mot Akalla respektive Hjulsta kan avg&aring; fr&aring;n b&aring;da sp&aring;ren. Vid os&auml;kerhet, ta n&auml;sta t&aring;g f&ouml;r byte till r&auml;tt destination senast vid V&auml;stra skogen.",
            "TransportMode":"METRO",
            "LineNumber":"11",
            "Destination":"Akalla",
            "JourneyDirection":1,
            "SiteId":9340
         }
      ],
      "Buses":[
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:17:39",
            "ExpectedDateTime":"2014-09-19T14:24:40",
            "DisplayTime":"1 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"62",
            "Destination":"Stor&auml;ngsbotten",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:27:18",
            "ExpectedDateTime":"2014-09-19T14:27:40",
            "DisplayTime":"4 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"76",
            "Destination":"Ropsten",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:28:05",
            "ExpectedDateTime":"2014-09-19T14:27:41",
            "DisplayTime":"4 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Sofia",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:23:48",
            "ExpectedDateTime":"2014-09-19T14:27:45",
            "DisplayTime":"4 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"76",
            "Destination":"Norra Hammarbyhamnen",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:26:32",
            "ExpectedDateTime":"2014-09-19T14:28:00",
            "DisplayTime":"4 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"55",
            "Destination":"Hjorthagen",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10326,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:26:15",
            "ExpectedDateTime":"2014-09-19T14:28:04",
            "DisplayTime":"4 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"62",
            "Destination":"Fredh&auml;ll",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:31:59",
            "ExpectedDateTime":"2014-09-19T14:31:59",
            "DisplayTime":"8 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"55",
            "Destination":"Sofia",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:26:39",
            "ExpectedDateTime":"2014-09-19T14:32:36",
            "DisplayTime":"8 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"62",
            "Destination":"Stor&auml;ngsbotten",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:28:40",
            "ExpectedDateTime":"2014-09-19T14:32:55",
            "DisplayTime":"9 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Norrtull",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:34:05",
            "ExpectedDateTime":"2014-09-19T14:34:08",
            "DisplayTime":"10 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Sofia",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:34:40",
            "ExpectedDateTime":"2014-09-19T14:35:11",
            "DisplayTime":"11 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Norrtull",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10326,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:35:15",
            "ExpectedDateTime":"2014-09-19T14:35:15",
            "DisplayTime":"11 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"62",
            "Destination":"Fredh&auml;ll",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:35:39",
            "ExpectedDateTime":"2014-09-19T14:36:54",
            "DisplayTime":"13 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"62",
            "Destination":"Stor&auml;ngsbotten",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10326,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:37:08",
            "ExpectedDateTime":"2014-09-19T14:37:08",
            "DisplayTime":"13 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"65",
            "Destination":"Vanadisplan",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:38:48",
            "ExpectedDateTime":"2014-09-19T14:39:04",
            "DisplayTime":"15 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"76",
            "Destination":"Norra Hammarbyhamnen",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:40:05",
            "ExpectedDateTime":"2014-09-19T14:39:06",
            "DisplayTime":"15 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Sofia",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:40:55",
            "ExpectedDateTime":"2014-09-19T14:41:43",
            "DisplayTime":"18 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Norrtull",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10326,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:33:14",
            "ExpectedDateTime":"2014-09-19T14:42:24",
            "DisplayTime":"18 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"43",
            "Destination":"Ruddammen",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-19T14:46:05",
            "ExpectedDateTime":"2014-09-19T14:42:55",
            "DisplayTime":"19 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Sofia",
            "SiteId":9340
         }
      ],
      "Trains":[

      ],
      "Trams":[

      ],
      "Ships":[

      ],
      "StopPointDeviations":[

      ]
   }
};