var mockResponse = {
   "StatusCode":0,
   "Message":null,
   "ExecutionTime":591,
   "ResponseData":{
      "LatestUpdate":"2014-09-09T14:53:14",
      "DataAge":35,
      "Metros":[
         {
            "StopAreaName":"Kungstr&auml;dg&aring;rden",
            "GroupOfLine":"Tunnelbanans bl&aring; linje",
            "DisplayTime":"1 min",
            "SafeDestinationName":"Hjulsta",
            "GroupOfLineId":3,
            "DepartureGroupId":1,
            "PlatformMessage":null,
            "TransportMode":"METRO",
            "LineNumber":"10",
            "Destination":"Hjulsta",
            "JourneyDirection":1,
            "SiteId":9340
         },
         {
            "StopAreaName":"Kungstr&auml;dg&aring;rden",
            "GroupOfLine":"Tunnelbanans bl&aring; linje",
            "DisplayTime":"5 min",
            "SafeDestinationName":"Akalla",
            "GroupOfLineId":3,
            "DepartureGroupId":1,
            "PlatformMessage":null,
            "TransportMode":"METRO",
            "LineNumber":"11",
            "Destination":"Akalla",
            "JourneyDirection":1,
            "SiteId":9340
         },
         {
            "StopAreaName":"Kungstr&auml;dg&aring;rden",
            "GroupOfLine":"Tunnelbanans bl&aring; linje",
            "DisplayTime":"9 min",
            "SafeDestinationName":"Hjulsta",
            "GroupOfLineId":3,
            "DepartureGroupId":1,
            "PlatformMessage":null,
            "TransportMode":"METRO",
            "LineNumber":"10",
            "Destination":"Hjulsta",
            "JourneyDirection":1,
            "SiteId":9340
         }
      ],
      "Buses":[
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10326,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T14:53:15",
            "ExpectedDateTime":"2014-09-09T14:53:15",
            "DisplayTime":"14:53",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"62",
            "Destination":"Fredh&auml;ll",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T14:53:39",
            "ExpectedDateTime":"2014-09-09T14:53:39",
            "DisplayTime":"14:53",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"62",
            "Destination":"Stor&auml;ngsbotten",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10326,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T14:57:08",
            "ExpectedDateTime":"2014-09-09T14:55:37",
            "DisplayTime":"1 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"65",
            "Destination":"Vanadisplan",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T14:53:48",
            "ExpectedDateTime":"2014-09-09T14:56:12",
            "DisplayTime":"2 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"76",
            "Destination":"Norra Hammarbyhamnen",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T14:57:18",
            "ExpectedDateTime":"2014-09-09T14:57:18",
            "DisplayTime":"3 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"76",
            "Destination":"Ropsten",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T14:58:55",
            "ExpectedDateTime":"2014-09-09T14:58:31",
            "DisplayTime":"4 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Norrtull",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T14:58:12",
            "ExpectedDateTime":"2014-09-09T14:58:47",
            "DisplayTime":"4 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"55",
            "Destination":"Hjorthagen",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T14:58:05",
            "ExpectedDateTime":"2014-09-09T14:58:55",
            "DisplayTime":"5 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Sofia",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:01:59",
            "ExpectedDateTime":"2014-09-09T15:01:05",
            "DisplayTime":"7 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"55",
            "Destination":"Sofia",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10326,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:02:15",
            "ExpectedDateTime":"2014-09-09T15:02:15",
            "DisplayTime":"15:02",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"62",
            "Destination":"Fredh&auml;ll",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:02:39",
            "ExpectedDateTime":"2014-09-09T15:02:39",
            "DisplayTime":"15:02",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"62",
            "Destination":"Stor&auml;ngsbotten",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10326,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:03:14",
            "ExpectedDateTime":"2014-09-09T15:03:14",
            "DisplayTime":"9 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"43",
            "Destination":"Ruddammen",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:04:05",
            "ExpectedDateTime":"2014-09-09T15:03:47",
            "DisplayTime":"9 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Sofia",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:04:55",
            "ExpectedDateTime":"2014-09-09T15:05:33",
            "DisplayTime":"11 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Norrtull",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:05:48",
            "ExpectedDateTime":"2014-09-09T15:06:19",
            "DisplayTime":"12 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"76",
            "Destination":"Norra Hammarbyhamnen",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:10:55",
            "ExpectedDateTime":"2014-09-09T15:09:03",
            "DisplayTime":"15 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Norrtull",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:10:18",
            "ExpectedDateTime":"2014-09-09T15:10:18",
            "DisplayTime":"15:10",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"76",
            "Destination":"Ropsten",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:10:05",
            "ExpectedDateTime":"2014-09-09T15:11:12",
            "DisplayTime":"17 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Sofia",
            "SiteId":9340
         },
         {
            "JourneyDirection":2,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10326,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:11:15",
            "ExpectedDateTime":"2014-09-09T15:11:15",
            "DisplayTime":"15:11",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"62",
            "Destination":"Fredh&auml;ll",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":null,
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10120,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:11:39",
            "ExpectedDateTime":"2014-09-09T15:11:39",
            "DisplayTime":"15:11",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"62",
            "Destination":"Stor&auml;ngsbotten",
            "SiteId":9340
         },
         {
            "JourneyDirection":1,
            "GroupOfLine":"bl&aring;buss",
            "StopAreaName":"Karl XII:s torg",
            "StopAreaNumber":10120,
            "StopPointNumber":10121,
            "StopPointDesignation":null,
            "TimeTabledDateTime":"2014-09-09T15:16:05",
            "ExpectedDateTime":"2014-09-09T15:13:05",
            "DisplayTime":"19 min",
            "Deviations":null,
            "TransportMode":"BUS",
            "LineNumber":"2",
            "Destination":"Sofia",
            "SiteId":9340
         }
      ],
      "Trains":[

      ],
      "Trams":[

      ],
      "Ships":[
         {
            "JourneyDirection":1,
            "GroupOfLine":"Waxholmsbolaget",
            "StopAreaName":"Str&ouml;mkajen",
            "StopAreaNumber":301,
            "StopPointNumber":301,
            "TimeTabledDateTime":"2014-09-09T15:00:00",
            "ExpectedDateTime":"2014-09-09T15:00:00",
            "DisplayTime":"15:00",
            "Deviations":null,
            "TransportMode":"SHIP",
            "LineNumber":"13",
            "Destination":"Husar&ouml;",
            "SiteId":9340
         }
      ],
      "StopPointDeviations":[

      ]
   }
};